# Generated by Django 3.2.8 on 2021-11-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtomodel',
            name='codigo',
            field=models.CharField(db_column='CODIGO', max_length=20, unique=True),
        ),
    ]
